artifacts_root: artifacts

# Used for getting data
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ameyagidh/TextSummarization/raw/master/research/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

